### PR TITLE
WIP Enhancement Compositional Shrinker

### PR DESCRIPTION
**Pull request by nicoabie**
This is an attempt to implement a compositional shrinker as described [in the Hypothesis blog](https://hypothesis.works/articles/compositional-shrinking/)

In order to merge this pull request, there are a few tasks that need to be addressed first:

- [X] Ability to create a composite with more than one arbitrary
- [X] Ability to use composite definition to check type without user intervention
- [ ] Add more tests and get feedback if possible

### CODE REVIEW

**Comment by pmoura** [comment]
Oops! Didn't notice the checklist!

I have doubts about the usefulness of the second item in the checklist, however. Usually, when we define an arbitrary generator for a  type, we already have a definition for the type.

**Comment by nicoabie** [comment]
Exactly my thinking. Only use case I can think of is the user testing a transformation to the composite and would like to assert its shape (type) is preserved.

I'll focus in the first item meanwhile as we agree would be useful

**Comment by nicoabie** [comment]
@pmoura I pushed the ability to create composites with any number of arbitraries, I have to work on more tests now, but in case you want to take a look into it please be my guest!

**Comment by pmoura** [comment]
One issue I see with the `composite/3` **static** predicate is that you're calling `clause/2` on it. This assumes that the `protect_static_code` is set to `false` (its default). The predicate also plays two different roles, one when we access its base types (in order to generate arbitrary values) and another one when we pass values for those types (in order to compute a shrink value from shrink base type values). If these two roles were separated, there would be no need to use `clause/2`. The downside is that this alternative would require the user to define two (multifile) predicates instead of just one (that's the approach used in Logtalk, btw, as most Prolog systems only allow using `clause/2` on dynamic predicates).

**Comment by pmoura** [comment]
P. S. Don't forget to also add a clause to `arbitrary_type/1` that returns types defined as composite.

**Comment by nicoabie** [comment]
> One issue I see with the `composite/3` **static** predicate is that you're calling `clause/2` on it. This assumes that the `protect_static_code` is set to `false` (its default). The predicate also plays two different roles, one when we access its base types (in order to generate arbitrary values) and another one when we pass values for those types (in order to compute a shrink value from shrink base type values). If these two roles were separated, there would be no need to use `clause/2`. The downside is that this alternative would require the user to define two (multifile) predicates instead of just one (that's the approach used in Logtalk, btw, as most Prolog systems only allow using `clause/2` on dynamic predicates).

Oh ok, I'm new to Prolog so I didn't know about it. So it is more like a compatibility issue. If we mark `composite/3` as **dynamic** can we solve this? Maybe losing some performance but I think the use of clause/2 is key here to find out what must be injected into the composite. 

> P. S. Don't forget to also add a clause to arbitrary_type/1 that returns types defined as composite.

I'm not sure about this one, composite the way I see it is not an arbitrary per se. I might be wrong.

**Comment by pmoura** [comment]
I suggest you don't make any changes for now do the issue discussed above with `clause/2`. Just wanted for you to be aware of it.

Regarding `arbitrary_type/1 `, it allows the user to find for which types we can generate arbitrary values. You can do that with all types defined as composites.

**Comment by nicoabie** [comment]
> I suggest you don't make any changes for now do the issue discussed above with `clause/2`. Just wanted for you to be aware of it.

Ok thanks, maybe that is a disclaimer that should be pointed out. 

> Regarding `arbitrary_type/1 `, it allows the user to find for which types we can generate arbitrary values. You can do that with all types defined as composites.

`arbitrary_type/1 ` does that but also is used in `arbitrary(any, X)` and I don't think from a user POV that will be desirable. I think the composite is defined for the user is some specific contexts.
Maybe a `composite_type/1` can be implemented just to list them. Sounds good?

**Comment by pmoura** [comment]
From the perspective of a QuickCheck user, the fact that some type is implemented as a composite is just an implementation detail. The main role of the `arbitrary_type/1 ` is to allow the user to find for which types QuickCheck can be used to test his/her predicates.

**Pull request merged**
